### ISSUE TITLE
Change configurable loggers to dictionary instead of list

### ISSUE THREAD

**Issue by ahayehaye** [not-mt/nmt-fastapi-library#13]
This will allow defaults to be inherited from files that are processed earlier in `APP_CONFIG_FILES`. For example, if this is in the `nmtfast-config-default.yaml` file:

```yaml
logging:
  level: DEBUG
  loggers:
    "aiosqlite":
      level: INFO
    "pymongo":
      level: INFO
```

Then an application specific config like this:

```yaml
logging:
  level: DEBUG
  loggers:
    "app.core.v1.auth":
      level: INFO
```

...will inherit the `aiosqlite` and `pymongo` settings, without having to redefine them.
